CREATE TABLE State
(name VARCHAR(256) NOT NULL PRIMARY KEY,
 kanye_vote INTEGER NOT NULL,
 not_kanye_vote INTEGER NOT NULL);

CREATE TABLE BlogUser
(username VARCHAR(256) NOT NULL PRIMARY KEY,
 password VARCHAR(256) NOT NULL);

CREATE TABLE BlogPost
(id VARCHAR(256) NOT NULL PRIMARY KEY,
 username VARCHAR(256) NOT NULL,
 message VARCHAR(256) NOT NULL,
 FOREIGN KEY (username) REFERENCES BlogUser(username));
